apiVersion: v1
kind: Service
metadata:
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:ports:
            .: {}
            k:{"port":80,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":443,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:app: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
  name: dkss-svc
  namespace: dkcs-local-ns
  resourceVersion: "18645879"
  selfLink: /api/v1/namespaces/dkcs-local-ns/services/dkss-svc
spec:
  clusterIP: 10.43.44.112
  ports:
    - name: http2
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app: dkss
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
